name:                backerei
version:             0.1.0.0
github:              "cryptiumlabs/backerei"
license:             MIT
author:              "Cryptium Labs"
maintainer:          "cwgoes@cryptium.ch"
copyright:           "2018 Cryptium Labs"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/cryptiumlabs/backerei#readme>

dependencies:
- base >= 4.7 && < 5
- foundation
- aeson
- text

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - NoMonomorphismRestriction
  - RankNTypes
  - LambdaCase
  - UnicodeSyntax
  - GADTs
  - ScopedTypeVariables
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - DataKinds
  - GeneralizedNewtypeDeriving

ghc-options:
  - -ferror-spans
  - -Wall
  - -fno-warn-orphans
  - -fno-warn-name-shadowing

library:
  source-dirs: src
  dependencies:
    - text
    - req
    - data-default-class
    - time

executables:
  backerei:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - backerei
    - gitrev
    - ansi-wl-pprint
    - optparse-applicative
    - directory
    - yaml
    - telegram-bot-simple
    - servant-client

tests:
  backerei-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - backerei
